const express = require('express');
const { SKILL_MAP, normalizeSkillKey } = require('../lib/skills');
const { searchYouTube, generateFallbackVideos } = require('../lib/youtubeVideos');
const { generateTasks } = require('../lib/geminiTasks');
const { getTrackTopics } = require('../lib/trackTopics');
const { getIntroItems } = require('../lib/introContent');

module.exports = function publicRoutes(admin, geminiModel) {
  const r = express.Router();

  /* ─────────────────────────────────────────────────────────────────
   * GET /api/public/content-pack?skill=aiml&level=Beginner
   *
   * Returns 7 video+task pairs:
   *  - Tasks: generated by Gemini (or static fallback)
   *  - Videos: one per task via YouTube API (or rotated fallback bucket)
   * ─────────────────────────────────────────────────────────────── */
  r.get('/api/public/content-pack', async (req, res) => {
    try {
      const skillKey = normalizeSkillKey(req.query.skill || 'aiml');
      const level    = req.query.level || 'Beginner';
      const sm       = SKILL_MAP[skillKey] || SKILL_MAP.aiml;

      // Get track curriculum topics for this domain+level
      const topics = getTrackTopics(skillKey, level);

      // 1. Generate topic-aligned tasks (Gemini or static)
      const tasks = await generateTasks(geminiModel, skillKey, level, topics);

      // 2. Try to get one specific video per task via YouTube API.
      //    If quota exceeded / error, get the full fallback bucket for this
      //    skill and rotate through it so every card shows a DIFFERENT video.
      let items;
      try {
        // Try a single probe request to see if quota is OK
        const probeQ = tasks[0]?.ytQuery || sm.query;
        const probe  = await searchYouTube(probeQ, 1);

        if (probe.source === 'youtube-api') {
          // Quota OK — fetch each task's matched video in parallel
          const videoPromises = tasks.map(async (task) => {
            const q = task.ytQuery || `${task.title} tutorial project`;
            try {
              const { videos } = await searchYouTube(q, 2);
              return videos[0] || null;
            } catch {
              return null;
            }
          });
          const videos = await Promise.all(videoPromises);
          items = tasks.map((task, i) => ({ video: videos[i] || null, task }));

        } else {
          // Quota exceeded — use topic-specific fallback videos
          // Each task's ytQuery drives its own fallback lookup
          const fallbackVideos = topics
            ? tasks.map((task) => generateFallbackVideos(task.ytQuery || sm.query, level)[0])
            : generateFallbackVideos(sm.query, level);
          items = tasks.map((task, i) => ({
            video: Array.isArray(fallbackVideos) ? (fallbackVideos[i] || fallbackVideos[i % fallbackVideos.length] || null) : fallbackVideos,
            task
          }));
        }
      } catch {
        // Last-resort: rotate fallback by topic query
        items = tasks.map((task) => ({
          video: generateFallbackVideos(task.ytQuery || sm.query, level)[0] || null,
          task
        }));
      }

      // Prepend beginner intro items (hardcoded curated videos, always present)
      if (level === 'Beginner') {
        const introItems = getIntroItems(skillKey);
        items = [...introItems, ...items];
      }

      res.json({ skillKey, level, source: tasks[0]?.source || 'gemini', items });
    } catch (e) {
      console.error('[content-pack]', e);
      res.status(500).json({ error: e.message || 'Pack failed.' });
    }
  });

  /* ─────────────────────────────────────────────────────────────────
   * GET /api/youtube/search?q=...&maxResults=6
   * ─────────────────────────────────────────────────────────────── */
  r.get('/api/youtube/search', async (req, res) => {
    const q = req.query.q;
    if (!q) return res.status(400).json({ error: 'Query required' });
    try {
      const { source, videos } = await searchYouTube(q, parseInt(req.query.maxResults || '6', 10));
      res.json({ success: true, source, videos });
    } catch {
      const { videos } = await searchYouTube(q);
      res.json({ success: true, source: 'fallback', videos });
    }
  });

  /* ─────────────────────────────────────────────────────────────────
   * GET /api/public/explore?skill=aiml
   * ─────────────────────────────────────────────────────────────── */
  r.get('/api/public/explore', async (req, res) => {
    try {
      const skillKey = normalizeSkillKey(req.query.skill || 'aiml');
      const level    = req.query.level || 'Beginner';
      const sm       = SKILL_MAP[skillKey] || SKILL_MAP.aiml;

      const allTasks = await generateTasks(geminiModel, skillKey, level);
      const tasks    = allTasks.slice(0, 7);

      // Rotate fallback / API videos across explore cards
      let videos = [];
      try {
        const probe = await searchYouTube(sm.query, 4);
        if (probe.source === 'youtube-api') {
          videos = probe.videos.slice(0, 4);
        } else {
          videos = generateFallbackVideos(sm.query).slice(0, 4);
        }
      } catch {
        videos = generateFallbackVideos(sm.query).slice(0, 4);
      }

      let counts = {};
      if (admin) {
        try {
          const { data: allDBTasks } = await admin.from('tasks').select('domain, level');
          const { SKILL_MAP: SM } = require('../lib/skills');
          for (const key of Object.keys(SM)) {
            counts[key] = (allDBTasks || []).filter(t => {
              const d = String(t.domain || '').toLowerCase();
              if (key === 'aiml')        return d.includes('ai') || d.includes('ml');
              if (key === 'datascience') return d.includes('data');
              if (key === 'robotics')    return d.includes('robot');
              if (key === 'iot')         return d.includes('iot');
              if (key === 'cybersec')    return d.includes('cyber') || d.includes('sec');
              if (key === 'webdev')      return d.includes('web');
              return false;
            }).length;
          }
        } catch { counts = {}; }
      }

      res.json({ skillKey, label: sm.label, tasks, videos, source: tasks[0]?.source || 'gemini', counts });
    } catch (e) {
      console.error('[explore]', e);
      res.status(500).json({ error: e.message || 'Explore failed.' });
    }
  });

  return r;
};
